name: Ghast Whisperer
main: com.crystalcraftmc.ghastwhisperer
version: ${version}

commands:
   ghastDisplay:
      usage:
         Used to customize ghast-riding
      command:
         <command>
   ghastRide:
      usage:
         Used to actually spawn the ghast and it's passengers
      command:
         <command>
