name: GhastWhisperer
main: com.crystalcraftmc.ghastwhisperer
version: 0.1.1
authors: [Jwood9198, jflory7]
website: http://crystalcraftmc.com

commands:
   ghastDisplay:
      usage: Used to customize ghast-riding
      command: /<command>
   ghastRide:
      usage: Used to actually spawn the ghast and it's passengers
      command: <command>
